volumes:
  db_data:

services:
  csa-redis:
    image: redis/redis-stack-server:latest 
    container_name: skyblock-ah-redis
    environment:
      - REDIS_ARGS=--requirepass password
    expose:
      - "6379"
    ports:
      - "6379:6379"
    networks:
      - overlay
networks:
  overlay: